"""Convert AutoSci report data to `scientific_report.v1` evidence."""

from __future__ import annotations

from typing import Any

from .common import evidence_base


def convert(raw: dict[str, Any], envelope: dict[str, Any] | None = None) -> dict[str, Any]:
    report = {
        "report_id": str(raw.get("report_id") or "report-001"),
        "title": str(raw.get("title") or "AutoSci Adapter Fixture Report"),
        "sections": list(raw.get("sections") or [
            {
                "section_id": "summary",
                "title": "Summary",
                "evidence_ids": ["claim-001", "exp-001"],
                "body": "Fixture report generated by the AutoSci adapter bridge.",
            }
        ]),
        "evidence_ids": list(raw.get("evidence_ids") or ["claim-001", "exp-001"]),
        "unsupported_claims": list(raw.get("unsupported_claims") or []),
    }
    return evidence_base("scientific_report.v1", envelope, {"report": report})
